# Generated by Django 3.2.6 on 2021-08-30 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coursehai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomapp11',
            name='image',
            field=models.ImageField(default='https://via.placeholder.com/500x500.png?text=Default', upload_to='course\\images'),
        ),
        migrations.AddField(
            model_name='ecomapp11',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
