# Generated by Django 3.2.6 on 2021-09-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursehai', '0004_alter_ecomapp11_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomapp11',
            name='category',
            field=models.CharField(default='Daily use', max_length=25),
        ),
    ]
