# Generated by Django 3.2.6 on 2021-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursehai', '0005_ecomapp11_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomapp11',
            name='category',
            field=models.CharField(default='Daily', max_length=25),
        ),
    ]
