# Generated by Django 3.2.6 on 2021-09-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursehai', '0009_alter_ecomapp11_extra_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecomapp11',
            name='extra_details',
        ),
    ]
