# Generated by Django 3.2.6 on 2021-09-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursehai', '0010_remove_ecomapp11_extra_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomapp11',
            name='extra_details',
            field=models.CharField(default="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries", max_length=500),
        ),
    ]
