# Generated by Django 3.2.6 on 2021-09-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursehai', '0012_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Image',
            field=models.ImageField(default='courseapp\\images\\shoe.jpg', upload_to='contact\\images'),
        ),
    ]
