# Generated by Django 3.2.6 on 2021-09-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursehai', '0014_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='jsonCart',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Image',
            field=models.ImageField(default='contact\\images\\shoe.jpg', upload_to='contact\\images'),
        ),
    ]
