# Generated by Django 3.2.6 on 2021-09-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursehai', '0015_auto_20210914_0137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
