# Generated by Django 3.2.6 on 2021-09-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursehai', '0019_auto_20210914_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jsonCart',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
