# Generated by Django 3.2.6 on 2021-09-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursehai', '0022_auto_20210915_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownshop',
            old_name='title',
            new_name='title1',
        ),
    ]
