# Generated by Django 3.2.6 on 2021-09-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursehai', '0023_rename_title_ownshop_title1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownshop',
            name='image1',
            field=models.ImageField(default='courseapp\\images\\shoe.jpg', upload_to='Blog\\images'),
        ),
    ]
