# Generated by Django 3.2.6 on 2021-09-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursehai', '0025_alter_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Image',
            field=models.ImageField(default='contact\\images\\shoe.jpg', upload_to='contact\\images'),
        ),
    ]
